language: node_js
os:
  - linux
  - osx
node_js:
  - 'lts/*'
before_install:
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn install
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn lint
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - yarn lh --perf=90 --pwa=100 --no-comment https://rinae.dev/
branches:
  only:
    - master
    - /^greenkeeper.*$/
