backend:
  name: git-gateway
  branch: master

media_folder: content/blog/images
public_folder: /images

collections:
  - name: 'blog'
    label: 'Blog Post'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{fields.slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          dateFormat: 'YYYY-MM-DD',
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - {
          label: 'Cover Image URL',
          name: 'coverImageUrl',
          widget: 'string',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
